### ISSUE TITLE
Accessibility 

### ISSUE THREAD

**Issue by RunGT** [fac21/week3-catalog-EM2C#32]
I can easily interact with the site with the tab button - great work

High score on light house 94%

**Comment by jamdelion** [comment]
+1 to this, we love that you have the aria-label that changes to be specific for each newtask ("delete the task for ${newtask}")

**Comment by RunGT** [comment]
Came back to say after noticing the dynamic aria labels for deleting tasks is a very nice touch!! 

Great accessibility design in action
