### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by RunGT** [fac21/week3-catalog-EM2C#34]
Good use of media queries.

From a styling stand point when view on a mobile such as an iPhone6, I would look at the positioning of the logo and the task section in relation to the logo.

I.e centralise the logo in mobile format and possibly add padding to the add a task section if it is too high on the page.

**Comment by Tiarama** [comment]
Changed logo & catchphrase size and placement for different media queries; as well as responsive content padding.
