### ISSUE TITLE
addNewTask() is quite long

### ISSUE THREAD

**Issue by jamdelion** [fac21/week3-catalog-EM2C#35]
We loved how simply written your other functions in script.js were (and we learned some interesting things that we'd like to apply to our code - like toggling the class for the strikethrough, and parentNode.parentNode). The addNewTask function is much much longer though, and a little harder to read. Perhaps you could consider splitting it into other functions or making it simpler somehow?

**Comment by RunGT** [comment]
I agree, it will be worth allocating some time to refactor your `addNewTask ` function
